### ISSUE TITLE
Вопросы

### ISSUE THREAD

**Issue by anton-petrov** [NikitaZemlin/STRPO#2]
1. Поясните, почему в вашем решение используется именно "делегирование", а не композиция (has a).
2. Приведите пример композиции, ассоциации, агрегации и/или их ключевые различия.

**Comment by NikitaZemlin** [comment]
1. Делегирование использовалось, чтобы расширить возможности класса минимальным кол-вом кода(использование методов другого класса). При делегировании не используется прямое наследство(как в наследовании). Композиция используется в тех случаях, когда нужно использовать функциональность уже существующего класса в другом новом классе (создаётся объект класса внутри класса, методы которого необходимо применить). Подытожив, можно сказать, что делегирование нечто среднее между наследованием и композицией.
2. ~в процессе

**Comment by anton-petrov** [comment]
Ok! Если объект класса напрямую объявляется и инстанцируется внутри метода другого класса, как у тебя, это  делегирование. То есть мы просто пользуемся функционалом других классов. Ответ засчитан!

**Comment by anton-petrov** [comment]
2...

**Comment by NikitaZemlin** [comment]
Добавил ответ на 2 вопрос.
